require_relative '../concerns/findable.rb'
require_relative '../concerns/populate.rb'
require_relative '../models/movie.rb'
require_relative '../models/actor.rb'
require_relative '../models/director.rb'
require_relative '../models/genre.rb'